-- Step 63 - Fix Vietnamese encoding for P1-01/M11 display data.
-- Run after database/step62_short_course_data_foundation.sql.
--
-- This patch only repairs Vietnamese display/governance metadata already inserted into Supabase.
-- It does not change table structure, permissions, RLS policies, or triggers.

insert into public.short_governance_rules (
  rule_code,
  rule_name,
  rule_group,
  rule_description,
  enforcement_level,
  source_table,
  target_process,
  owner_department,
  checker_role,
  approver_role,
  ai_allowed,
  control_status,
  status
) values
  (
    'SHORT_ATTENDANCE_REQUIRED_FOR_BHXH',
    'Có điểm danh mới xử lý BHXH/chính sách',
    'BHXH',
    'Không tạo hồ sơ BHXH/chính sách hỗ trợ nếu lớp chưa có buổi học hoặc học viên chưa có dữ liệu điểm danh hợp lệ.',
    'BLOCK',
    'short_attendance_records',
    'BHXH_POLICY_CASE',
    'DAO_TAO + KHTC',
    'KHTC + DAO_TAO',
    'BGH',
    true,
    'DAT_TAM_THOI',
    'ACTIVE'::public.record_status
  ),
  (
    'SHORT_PAYMENT_REQUIRES_INVOICE_AND_APPROVAL',
    'Thanh toán phải có phiếu thu/công nợ và quyền xác nhận',
    'FINANCE',
    'Không ghi nhận thanh toán nếu chưa có invoice hoặc người xác nhận không có quyền tài chính.',
    'APPROVAL_REQUIRED',
    'short_finance_invoices',
    'SHORT_PAYMENT',
    'KHTC',
    'ACCOUNTING_LEAD',
    'BGH',
    true,
    'DAT_TAM_THOI',
    'ACTIVE'::public.record_status
  ),
  (
    'SHORT_LOCKED_DATA_NO_DIRECT_EDIT',
    'Dữ liệu đã khóa không sửa trực tiếp',
    'DATA_LOCK',
    'Học viên, lớp, điểm danh hoặc tài chính đã khóa phải mở yêu cầu duyệt trước khi sửa.',
    'APPROVAL_REQUIRED',
    'short_student_master,short_class_master,short_attendance_sessions,short_finance_invoices',
    'DATA_CORRECTION',
    'IT_DATA + PHAP_CHE',
    'AUDIT + TRUONG_PHONG',
    'BGH',
    true,
    'DAT_TAM_THOI',
    'ACTIVE'::public.record_status
  )
on conflict (rule_code) do update set
  rule_name = excluded.rule_name,
  rule_group = excluded.rule_group,
  rule_description = excluded.rule_description,
  enforcement_level = excluded.enforcement_level,
  source_table = excluded.source_table,
  target_process = excluded.target_process,
  owner_department = excluded.owner_department,
  checker_role = excluded.checker_role,
  approver_role = excluded.approver_role,
  ai_allowed = excluded.ai_allowed,
  control_status = excluded.control_status,
  status = 'ACTIVE',
  updated_at = now();

insert into public.heu_os_modules (
  module_code,
  module_name,
  module_group,
  objective,
  owner_department,
  core_policy,
  ai_policy,
  sort_order,
  control_status
) values (
  'M11_SHORT_COURSE_ERP',
  'ERP ngắn hạn',
  'CORE_OPERATION',
  'Quản lý học viên ngắn hạn, lớp, điểm danh, BHXH/chính sách, công nợ và thanh toán.',
  'DAO_TAO + TUYEN_SINH + CTHSSV + KHTC',
  'Student ID và Class ID là xương sống; điểm danh là nguồn dữ liệu gốc; thanh toán phải qua governance.',
  'AI chỉ hỗ trợ phát hiện thiếu điểm danh, sai công nợ, rủi ro BHXH/thanh toán; không tự duyệt.',
  110,
  'DAT_TAM_THOI'
) on conflict (module_code) do update set
  module_name = excluded.module_name,
  module_group = excluded.module_group,
  objective = excluded.objective,
  owner_department = excluded.owner_department,
  core_policy = excluded.core_policy,
  ai_policy = excluded.ai_policy,
  sort_order = excluded.sort_order,
  control_status = excluded.control_status,
  status = 'ACTIVE',
  updated_at = now();

insert into public.heu_os_workflows (
  workflow_code,
  workflow_name,
  module_code,
  trigger_event,
  start_role,
  owner_department,
  checker_role,
  approver_role,
  output_result,
  handover_rule,
  audit_rule,
  sort_order,
  control_status
) values (
  'WF_P1_01_SHORT_DATA_FOUNDATION',
  'P1-01 Xương sống dữ liệu ERP ngắn hạn',
  'M11_SHORT_COURSE_ERP',
  'Lead ngắn hạn đủ điều kiện hoặc lớp ngắn hạn được mở.',
  'TUYEN_SINH/DAO_TAO',
  'DAO_TAO + CTHSSV + KHTC + IT_DATA',
  'PHAP_CHE + KHTC + TRUONG_PHONG',
  'BGH',
  'Có bảng dữ liệu chuẩn để vận hành Student, Class, Enrollment, Attendance, BHXH, Finance và Payment.',
  'Lead đủ điều kiện chuyển sang short_student_master; lớp dùng short_class_master; tiền dùng short_finance_invoices/short_payments.',
  'Mọi bảng P1-01 có trigger audit; dữ liệu đã khóa phải mở approval request trước khi sửa.',
  601,
  'DAT_TAM_THOI'
) on conflict (workflow_code) do update set
  workflow_name = excluded.workflow_name,
  module_code = excluded.module_code,
  trigger_event = excluded.trigger_event,
  start_role = excluded.start_role,
  owner_department = excluded.owner_department,
  checker_role = excluded.checker_role,
  approver_role = excluded.approver_role,
  output_result = excluded.output_result,
  handover_rule = excluded.handover_rule,
  audit_rule = excluded.audit_rule,
  sort_order = excluded.sort_order,
  control_status = excluded.control_status,
  updated_at = now();

insert into public.heu_os_approval_matrix (
  approval_code,
  module_code,
  workflow_code,
  decision_name,
  decision_level,
  maker_role,
  checker_role,
  approver_role,
  required_evidence,
  blocking_rule,
  sla_hours,
  control_status
) values
  (
    'APPROVE_SHORT_STUDENT_MASTER',
    'M11_SHORT_COURSE_ERP',
    'WF_P1_01_SHORT_DATA_FOUNDATION',
    'Duyệt chuyển lead ngắn hạn thành học viên',
    'DEPARTMENT',
    'TUYEN_SINH/CTHSSV',
    'TRUONG_PHONG_TUYEN_SINH + CTHSSV_LEAD',
    'BGH',
    'Lead ngắn hạn, ngành/khoá, hồ sơ tối thiểu và trạng thái đủ điều kiện.',
    'Chặn nếu lead không thuộc workspace ngắn hạn, thiếu offering hoặc trùng student_code.',
    48,
    'DAT_TAM_THOI'
  ),
  (
    'APPROVE_SHORT_ATTENDANCE_LOCK',
    'M11_SHORT_COURSE_ERP',
    'WF_P1_01_SHORT_DATA_FOUNDATION',
    'Duyệt khóa điểm danh lớp ngắn hạn',
    'DEPARTMENT',
    'DAO_TAO',
    'DAO_TAO + CTHSSV',
    'BGH',
    'Danh sách buổi học, điểm danh từng học viên và minh chứng nếu có.',
    'Chặn xử lý BHXH/chính sách nếu điểm danh chưa khóa hoặc thiếu dữ liệu.',
    24,
    'DAT_TAM_THOI'
  ),
  (
    'APPROVE_SHORT_PAYMENT_VERIFY',
    'M11_SHORT_COURSE_ERP',
    'WF_P1_01_SHORT_DATA_FOUNDATION',
    'Duyệt xác nhận thanh toán ngắn hạn',
    'FINANCE',
    'KHTC',
    'ACCOUNTING_LEAD',
    'BGH',
    'Invoice, chứng từ thanh toán, người nộp, số tiền và đối soát ngân hàng/quỹ.',
    'Chặn nếu chưa có invoice, thiếu chứng từ hoặc user không có quyền xác nhận.',
    24,
    'DAT_TAM_THOI'
  )
on conflict (approval_code) do update set
  module_code = excluded.module_code,
  workflow_code = excluded.workflow_code,
  decision_name = excluded.decision_name,
  decision_level = excluded.decision_level,
  maker_role = excluded.maker_role,
  checker_role = excluded.checker_role,
  approver_role = excluded.approver_role,
  required_evidence = excluded.required_evidence,
  blocking_rule = excluded.blocking_rule,
  sla_hours = excluded.sla_hours,
  control_status = excluded.control_status,
  status = 'ACTIVE',
  updated_at = now();

insert into public.heu_os_master_data_map (
  data_code,
  data_name,
  module_code,
  source_table,
  data_type,
  owner_department,
  system_of_record,
  sensitivity_level,
  ai_allowed,
  change_rule,
  control_status
) values
  (
    'MD_P1_01_SHORT_STUDENT_MASTER',
    'Student Master ngắn hạn',
    'M11_SHORT_COURSE_ERP',
    'short_student_master',
    'MASTER',
    'CTHSSV + DAO_TAO + IT_DATA',
    'HEU_OS',
    'CONFIDENTIAL',
    true,
    'Student ID là định danh xuyên hệ thống; không sửa dữ liệu đã khóa nếu chưa có approval.',
    'DAT_TAM_THOI'
  ),
  (
    'MD_P1_01_SHORT_CLASS_MASTER',
    'Class Master ngắn hạn',
    'M11_SHORT_COURSE_ERP',
    'short_class_master',
    'MASTER',
    'DAO_TAO + IT_DATA',
    'HEU_OS',
    'INTERNAL',
    true,
    'Class ID là trung tâm cho điểm danh, BHXH, tài chính và dashboard.',
    'DAT_TAM_THOI'
  ),
  (
    'MD_P1_01_SHORT_ENROLLMENT',
    'Ghi danh học viên ngắn hạn',
    'M11_SHORT_COURSE_ERP',
    'short_enrollments',
    'TRANSACTION',
    'DAO_TAO + CTHSSV',
    'HEU_OS',
    'CONFIDENTIAL',
    true,
    'Enrollment nối Student, Class, Offering và trạng thái tài chính/BHXH.',
    'DAT_TAM_THOI'
  ),
  (
    'MD_P1_01_SHORT_ATTENDANCE',
    'Điểm danh ngắn hạn',
    'M11_SHORT_COURSE_ERP',
    'short_attendance_sessions,short_attendance_records',
    'TRANSACTION',
    'DAO_TAO',
    'HEU_OS',
    'CONFIDENTIAL',
    true,
    'Attendance là nguồn dữ liệu gốc; không có attendance thì không xử lý BHXH/chính sách.',
    'DAT_TAM_THOI'
  ),
  (
    'MD_P1_01_SHORT_FINANCE_PAYMENT',
    'Công nợ và thanh toán ngắn hạn',
    'M11_SHORT_COURSE_ERP',
    'short_finance_invoices,short_payments',
    'TRANSACTION',
    'KHTC',
    'HEU_OS',
    'RESTRICTED',
    true,
    'Thanh toán phải có invoice, chứng từ và người xác nhận đúng quyền.',
    'DAT_TAM_THOI'
  )
on conflict (data_code) do update set
  data_name = excluded.data_name,
  module_code = excluded.module_code,
  source_table = excluded.source_table,
  data_type = excluded.data_type,
  owner_department = excluded.owner_department,
  system_of_record = excluded.system_of_record,
  sensitivity_level = excluded.sensitivity_level,
  ai_allowed = excluded.ai_allowed,
  change_rule = excluded.change_rule,
  control_status = excluded.control_status,
  status = 'ACTIVE',
  updated_at = now();

insert into public.heu_os_risk_controls (
  risk_code,
  risk_name,
  module_code,
  risk_group,
  severity,
  owner_department,
  risk_description,
  control_rule,
  escalation_rule,
  dashboard_metric,
  control_status
) values
  (
    'RISK_P1_01_SHORT_STUDENT_DUPLICATE',
    'Trùng học viên ngắn hạn',
    'M11_SHORT_COURSE_ERP',
    'DATA_QUALITY',
    'HIGH',
    'CTHSSV + IT_DATA',
    'Một người học bị tạo nhiều Student ID làm sai điểm danh, công nợ, BHXH và dashboard.',
    'Kiểm tra lead_id, số điện thoại, CCCD và student_code trước khi chuyển lead thành student.',
    'Nếu nghi trùng phải tạo risk alert và trưởng bộ phận duyệt xử lý merge/sửa.',
    'Số học viên có cùng SĐT/CCCD; số risk duplicate còn mở.',
    'DAT_TAM_THOI'
  ),
  (
    'RISK_P1_01_SHORT_ATTENDANCE_MISSING',
    'Thiếu điểm danh nhưng xử lý BHXH/tài chính',
    'M11_SHORT_COURSE_ERP',
    'COMPLIANCE',
    'CRITICAL',
    'DAO_TAO + KHTC',
    'Nếu không có điểm danh mà vẫn xử lý BHXH/chính sách hoặc thanh toán liên quan thì sai nguồn dữ liệu gốc.',
    'short_governance_rules chặn quy trình BHXH/chính sách khi chưa có attendance hợp lệ.',
    'Báo BGH/KHTC nếu phát hiện hồ sơ BHXH/chính sách thiếu attendance.',
    'Số hồ sơ BHXH/chính sách thiếu attendance; số lớp chưa khóa điểm danh.',
    'DAT_TAM_THOI'
  ),
  (
    'RISK_P1_01_SHORT_PAYMENT_WITHOUT_APPROVAL',
    'Thanh toán ngắn hạn thiếu chứng từ/quyền duyệt',
    'M11_SHORT_COURSE_ERP',
    'FINANCE_CONTROL',
    'CRITICAL',
    'KHTC',
    'Ghi nhận thanh toán khi chưa có invoice/chứng từ/người xác nhận đúng quyền làm sai công nợ và kế toán.',
    'short_payments phải gắn invoice, số tiền dương, chứng từ nếu có và verified_by đúng quyền.',
    'Kế toán trưởng/BGH xử lý nếu có thanh toán bị nghi sai.',
    'Số payment PENDING/REJECTED; số invoice còn balance.',
    'DAT_TAM_THOI'
  )
on conflict (risk_code) do update set
  risk_name = excluded.risk_name,
  module_code = excluded.module_code,
  risk_group = excluded.risk_group,
  severity = excluded.severity,
  owner_department = excluded.owner_department,
  risk_description = excluded.risk_description,
  control_rule = excluded.control_rule,
  escalation_rule = excluded.escalation_rule,
  dashboard_metric = excluded.dashboard_metric,
  control_status = excluded.control_status,
  status = 'ACTIVE',
  updated_at = now();

insert into public.data_dictionary_tables (
  table_code,
  table_name,
  module_code,
  table_type,
  data_owner_department,
  purpose,
  sensitivity_level,
  ai_allowed,
  control_status
) values
  ('short_student_master', 'Student Master ngắn hạn', 'M11_SHORT_COURSE_ERP', 'MASTER', 'CTHSSV + DAO_TAO', 'Định danh học viên ngắn hạn xuyên hệ thống.', 'CONFIDENTIAL', true, 'DAT_TAM_THOI'),
  ('short_class_master', 'Class Master ngắn hạn', 'M11_SHORT_COURSE_ERP', 'MASTER', 'DAO_TAO', 'Quản lý lớp, lịch, giảng viên, địa điểm và trạng thái lớp.', 'INTERNAL', true, 'DAT_TAM_THOI'),
  ('short_enrollments', 'Ghi danh ngắn hạn', 'M11_SHORT_COURSE_ERP', 'TRANSACTION', 'DAO_TAO + CTHSSV', 'Nối học viên với lớp/khoá và trạng thái vận hành.', 'CONFIDENTIAL', true, 'DAT_TAM_THOI'),
  ('short_attendance_sessions', 'Buổi điểm danh ngắn hạn', 'M11_SHORT_COURSE_ERP', 'TRANSACTION', 'DAO_TAO', 'Danh sách buổi học làm gốc cho attendance.', 'CONFIDENTIAL', true, 'DAT_TAM_THOI'),
  ('short_attendance_records', 'Dòng điểm danh ngắn hạn', 'M11_SHORT_COURSE_ERP', 'TRANSACTION', 'DAO_TAO', 'Nguồn dữ liệu gốc cho BHXH/chính sách/cảnh báo bỏ học.', 'CONFIDENTIAL', true, 'DAT_TAM_THOI'),
  ('short_bhxh_policy_cases', 'Hồ sơ BHXH/chính sách ngắn hạn', 'M11_SHORT_COURSE_ERP', 'TRANSACTION', 'KHTC + DAO_TAO', 'Theo dõi điều kiện/chứng từ chính sách hỗ trợ nếu có.', 'RESTRICTED', true, 'DAT_TAM_THOI'),
  ('short_finance_invoices', 'Công nợ ngắn hạn', 'M11_SHORT_COURSE_ERP', 'TRANSACTION', 'KHTC', 'Theo dõi phải thu, giảm trừ, đã thu và còn phải thu.', 'RESTRICTED', true, 'DAT_TAM_THOI'),
  ('short_payments', 'Thanh toán ngắn hạn', 'M11_SHORT_COURSE_ERP', 'TRANSACTION', 'KHTC', 'Ghi nhận chứng từ thanh toán đã/đang xác nhận.', 'RESTRICTED', true, 'DAT_TAM_THOI'),
  ('short_governance_rules', 'Rule governance ngắn hạn', 'M11_SHORT_COURSE_ERP', 'CONFIG', 'PHAP_CHE + IT_DATA', 'Quy tắc chặn/cảnh báo cho vận hành ngắn hạn.', 'INTERNAL', true, 'DAT_TAM_THOI'),
  ('short_risk_alerts', 'Cảnh báo rủi ro ngắn hạn', 'M11_SHORT_COURSE_ERP', 'TRANSACTION', 'DAO_TAO + KHTC + AUDIT', 'Theo dõi cảnh báo vận hành, tài chính, BHXH và dữ liệu.', 'INTERNAL', true, 'DAT_TAM_THOI')
on conflict (table_code) do update set
  table_name = excluded.table_name,
  module_code = excluded.module_code,
  table_type = excluded.table_type,
  data_owner_department = excluded.data_owner_department,
  purpose = excluded.purpose,
  sensitivity_level = excluded.sensitivity_level,
  ai_allowed = excluded.ai_allowed,
  control_status = excluded.control_status,
  updated_at = now();

insert into public.process_ownership_matrix (
  ownership_code,
  process_name,
  module_code,
  workflow_code,
  entity_type,
  source_table,
  owner_department,
  maker_role,
  checker_role,
  approver_role,
  viewer_scope,
  handover_from_department,
  handover_to_department,
  required_evidence,
  audit_rule,
  sla_hours,
  risk_level,
  control_status,
  status
) values (
  'OWN_P1_01_SHORT_COURSE_DATA_FOUNDATION',
  'Xây xương sống dữ liệu vận hành ngắn hạn',
  'M11_SHORT_COURSE_ERP',
  'WF_P1_01_SHORT_DATA_FOUNDATION',
  'DATA_FOUNDATION',
  'short_student_master,short_class_master,short_enrollments,short_attendance_records,short_finance_invoices,short_payments',
  'DAO_TAO + CTHSSV + KHTC + IT_DATA',
  'IT_DATA',
  'DAO_TAO + KHTC + PHAP_CHE',
  'BGH',
  'ROLE_AND_SCOPE',
  'TUYEN_SINH',
  'DAO_TAO + CTHSSV + KHTC',
  'Catalog P0-21, lead đủ điều kiện, hồ sơ/lớp/học phí/chứng từ nếu có.',
  'Mọi bảng P1-01 có audit trigger; dữ liệu đã khóa không sửa trực tiếp.',
  72,
  'CRITICAL',
  'DAT_TAM_THOI',
  'ACTIVE'::public.record_status
) on conflict (ownership_code) do update set
  process_name = excluded.process_name,
  module_code = excluded.module_code,
  workflow_code = excluded.workflow_code,
  entity_type = excluded.entity_type,
  source_table = excluded.source_table,
  owner_department = excluded.owner_department,
  maker_role = excluded.maker_role,
  checker_role = excluded.checker_role,
  approver_role = excluded.approver_role,
  viewer_scope = excluded.viewer_scope,
  handover_from_department = excluded.handover_from_department,
  handover_to_department = excluded.handover_to_department,
  required_evidence = excluded.required_evidence,
  audit_rule = excluded.audit_rule,
  sla_hours = excluded.sla_hours,
  risk_level = excluded.risk_level,
  control_status = excluded.control_status,
  status = 'ACTIVE',
  updated_at = now();

insert into public.decision_gates (
  gate_code,
  gate_name,
  gate_type,
  entity_type,
  entity_code,
  owner_department,
  checker_note,
  approver_note,
  decision_status,
  record_status
) values (
  'GATE_P1_01_SHORT_DATA_FOUNDATION_READY',
  'P1-01 Xương sống dữ liệu ngắn hạn sẵn sàng',
  'DATA',
  'SHORT_COURSE_ERP',
  'P1_01_SHORT_DATA_FOUNDATION',
  'DAO_TAO + CTHSSV + KHTC + IT_DATA',
  'Kiểm tra đủ bảng, RLS, audit trigger, data dictionary, ownership và governance rule.',
  'BGH duyệt trước khi mở P1-02 Lead -> Student tự động hoặc AI agent can thiệp.',
  'PENDING',
  'ACTIVE'::public.record_status
) on conflict (gate_code) do update set
  gate_name = excluded.gate_name,
  gate_type = excluded.gate_type,
  entity_type = excluded.entity_type,
  entity_code = excluded.entity_code,
  owner_department = excluded.owner_department,
  checker_note = excluded.checker_note,
  approver_note = excluded.approver_note,
  decision_status = excluded.decision_status,
  record_status = 'ACTIVE',
  updated_at = now();

insert into public.heu_os_navigation_nodes (
  node_code,
  node_name,
  node_group,
  module_code,
  href,
  summary,
  owner_department,
  primary_action,
  sort_order,
  is_core,
  requires_attention_rule,
  control_status
) values (
  'NAV_P1_01_SHORT_COURSE_ERP',
  'ERP ngắn hạn',
  'OPERATION',
  'M11_SHORT_COURSE_ERP',
  '/master-control/modules/M11_SHORT_COURSE_ERP',
  'Xương sống dữ liệu học viên, lớp, điểm danh, BHXH/chính sách, công nợ và thanh toán ngắn hạn.',
  'DAO_TAO + CTHSSV + KHTC',
  'Xem readiness P1-01',
  212,
  true,
  'Cần chú ý nếu chưa có class/enrollment/attendance hoặc payment thiếu invoice/approval.',
  'DAT_TAM_THOI'
) on conflict (node_code) do update set
  node_name = excluded.node_name,
  node_group = excluded.node_group,
  module_code = excluded.module_code,
  href = excluded.href,
  summary = excluded.summary,
  owner_department = excluded.owner_department,
  primary_action = excluded.primary_action,
  sort_order = excluded.sort_order,
  is_core = excluded.is_core,
  requires_attention_rule = excluded.requires_attention_rule,
  control_status = excluded.control_status,
  status = 'ACTIVE',
  updated_at = now();

