import {
  TASK_CENTER_READONLY_ADAPTER_DISABLED_BY_DEFAULT,
  TASK_CENTER_READONLY_ADAPTER_FEATURE_FLAG_REQUIRED,
  TASK_CENTER_READONLY_ADAPTER_NO_AI_OR_AUTOMATION,
  TASK_CENTER_READONLY_ADAPTER_NO_DATABASE_CLIENT,
  TASK_CENTER_READONLY_ADAPTER_NO_DATABASE_READ,
  TASK_CENTER_READONLY_ADAPTER_NO_SQL_MIGRATION,
  TASK_CENTER_READONLY_ADAPTER_NO_TASK_MUTATION,
  TASK_CENTER_READONLY_ADAPTER_SKELETON_ONLY,
} from "@/lib/task-center-readonly-adapter-skeleton";

export const TASK_CENTER_READONLY_ADAPTER_ENABLEMENT_GATE_ONLY =
  "TASK_CENTER_READONLY_ADAPTER_ENABLEMENT_GATE_ONLY";
export const TASK_CENTER_ADAPTER_ENABLEMENT_OWNER_REVIEW_REQUIRED =
  "OWNER_REVIEW_REQUIRED_BEFORE_DB_READ";
export const TASK_CENTER_ADAPTER_ENABLEMENT_DEFAULT_NO_GO =
  "ADAPTER_ENABLEMENT_DEFAULT_NO_GO";
export const TASK_CENTER_ADAPTER_DATABASE_READ_BLOCKED =
  "DATABASE_READ_BLOCKED";
export const TASK_CENTER_ADAPTER_ENABLEMENT_NO_DATABASE_CLIENT =
  "NO_DATABASE_CLIENT_CREATED";
export const TASK_CENTER_ADAPTER_ENABLEMENT_NO_DATABASE_READ =
  "NO_DATABASE_READ_EXECUTED";
export const TASK_CENTER_ADAPTER_ENABLEMENT_NO_SQL_MIGRATION =
  "NO_SQL_MIGRATION_CREATED";
export const TASK_CENTER_ADAPTER_ENABLEMENT_NO_TASK_MUTATION =
  "NO_TASK_MUTATION_ROUTE_CREATED";
export const TASK_CENTER_ADAPTER_ENABLEMENT_NO_AI_OR_AUTOMATION =
  "NO_AI_CALL_NO_AUTOMATION_STEP";

export type TaskCenterEnablementOwnerLane =
  | "IT_DATA"
  | "AUDIT"
  | "PHAP_CHE"
  | "DEPARTMENT_OWNER"
  | "BGH";

export type TaskCenterEnablementDecision =
  | "NO_GO"
  | "CAN_SUA"
  | "CHO_BGH_DUYET";

export type TaskCenterReadonlyAdapterEnablementGate = {
  mode: typeof TASK_CENTER_READONLY_ADAPTER_ENABLEMENT_GATE_ONLY;
  adapterMode: typeof TASK_CENTER_READONLY_ADAPTER_SKELETON_ONLY;
  adapterStatus: typeof TASK_CENTER_READONLY_ADAPTER_DISABLED_BY_DEFAULT;
  defaultDecision: typeof TASK_CENTER_ADAPTER_ENABLEMENT_DEFAULT_NO_GO;
  decision: "NO_GO";
  canEnableDatabaseRead: false;
  databaseReadState: typeof TASK_CENTER_ADAPTER_DATABASE_READ_BLOCKED;
  featureFlag: typeof TASK_CENTER_READONLY_ADAPTER_FEATURE_FLAG_REQUIRED;
  ownerReview: Record<TaskCenterEnablementOwnerLane, TaskCenterEnablementDecision>;
  requiredProof: readonly string[];
  boundary: {
    ownerReviewRequired: typeof TASK_CENTER_ADAPTER_ENABLEMENT_OWNER_REVIEW_REQUIRED;
    noDatabaseClient: typeof TASK_CENTER_ADAPTER_ENABLEMENT_NO_DATABASE_CLIENT;
    noDatabaseRead: typeof TASK_CENTER_ADAPTER_ENABLEMENT_NO_DATABASE_READ;
    noSqlMigration: typeof TASK_CENTER_ADAPTER_ENABLEMENT_NO_SQL_MIGRATION;
    noTaskMutation: typeof TASK_CENTER_ADAPTER_ENABLEMENT_NO_TASK_MUTATION;
    noAiOrAutomation: typeof TASK_CENTER_ADAPTER_ENABLEMENT_NO_AI_OR_AUTOMATION;
  };
};

export function createTaskCenterReadonlyAdapterEnablementGate(): TaskCenterReadonlyAdapterEnablementGate {
  return {
    mode: TASK_CENTER_READONLY_ADAPTER_ENABLEMENT_GATE_ONLY,
    adapterMode: TASK_CENTER_READONLY_ADAPTER_SKELETON_ONLY,
    adapterStatus: TASK_CENTER_READONLY_ADAPTER_DISABLED_BY_DEFAULT,
    defaultDecision: TASK_CENTER_ADAPTER_ENABLEMENT_DEFAULT_NO_GO,
    decision: "NO_GO",
    canEnableDatabaseRead: false,
    databaseReadState: TASK_CENTER_ADAPTER_DATABASE_READ_BLOCKED,
    featureFlag: TASK_CENTER_READONLY_ADAPTER_FEATURE_FLAG_REQUIRED,
    ownerReview: {
      IT_DATA: "NO_GO",
      AUDIT: "NO_GO",
      PHAP_CHE: "NO_GO",
      DEPARTMENT_OWNER: "NO_GO",
      BGH: "NO_GO",
    },
    requiredProof: [
      "IT_DATA_SCOPE_FIRST_FILTER_SIGNOFF",
      "AUDIT_NEGATIVE_ACCESS_EVIDENCE",
      "PHAP_CHE_RESTRICTED_DATA_BOUNDARY_SIGNOFF",
      "DEPARTMENT_OWNER_TASK_LABEL_ACCEPTANCE",
      "BGH_PRODUCTION_NO_GO_ACKNOWLEDGEMENT",
      "BACKUP_ROLLBACK_UAT_EVIDENCE_BEFORE_DB_READ",
    ],
    boundary: {
      ownerReviewRequired: TASK_CENTER_ADAPTER_ENABLEMENT_OWNER_REVIEW_REQUIRED,
      noDatabaseClient: TASK_CENTER_READONLY_ADAPTER_NO_DATABASE_CLIENT,
      noDatabaseRead: TASK_CENTER_READONLY_ADAPTER_NO_DATABASE_READ,
      noSqlMigration: TASK_CENTER_READONLY_ADAPTER_NO_SQL_MIGRATION,
      noTaskMutation: TASK_CENTER_READONLY_ADAPTER_NO_TASK_MUTATION,
      noAiOrAutomation: TASK_CENTER_READONLY_ADAPTER_NO_AI_OR_AUTOMATION,
    },
  };
}
